{   'Command': {   'Mission': {   'ABORT': [],
                                  'ALLOW_DEPLOY': [],
                                  'HOLD': [],
                                  'LAND': [],
                                  'LOITER': [],
                                  'NAVIGATE_TO': [   {   'bitmask': False,
                                                         'datatype': 'bytes',
                                                         'name': 'packed_mgrs'}],
                                  'PROCEED': [],
                                  'REASSIGN': [],
                                  'REROUTE': [],
                                  'SET_MISSION': [   {   'bitmask': False,
                                                         'datatype': 'int',
                                                         'name': 'mission_index'}],
                                  'SET_MISSION_MODE': [],
                                  'SET_WAYPOINT': [],
                                  'SET_ZONE': [],
                                  'SWARM_CONTROL': [],
                                  'TAKEOFF': []},
                   'System': {   'ACTIVATE': [],
                                 'DATALINK_CONFIG': [],
                                 'SET_FLIGHT_MODE': [],
                                 'SET_FLIGHT_PARAMETERS': [],
                                 'SHUTDOWN': [],
                                 'SWITCH_DATALINK': []}},
    'Data': {   'Mission': {   'QUERY_CONTACTS': [],
                               'QUERY_MISSION_ID': [],
                               'QUERY_MISSION_PROGRESS': [],
                               'QUERY_SWARM_INFO': []},
                'System': {   'QUERY_DATALINK_STATUS': [],
                              'QUERY_LOG_DATA': [],
                              'QUERY_NETWORK_STATUS': [],
                              'QUERY_SENSOR_DATA': [],
                              'QUERY_SYSTEM_HEALTH': [],
                              'QUERY_TELEMETRY': []}},
    'Event': {   'Mission': {   'PHASE': [   {   'bitmask': False,
                                                 'datatype': 'enum',
                                                 'name': 'MissionPhase'}]},
                 'System': {   'ACK': [   {   'bitmask': False,
                                              'datatype': 'int',
                                              'name': 'msgid'},
                                          {   'bitmask': False,
                                              'datatype': 'int',
                                              'name': 'rxtime'},
                                          {   'bitmask': False,
                                              'datatype': 'int',
                                              'name': 'rssi'}],
                               'ERROR': [],
                               'FAILSAFE': [],
                               'GPS_FIX': [],
                               'HW_FAILURE': [],
                               'ONLINE': [],
                               'RADIO': [],
                               'RF_EVENT': []}},
    'Heartbeat': {'System': {'HEARTBEAT': []}},
    'Status': {   'Mission': {   'MISSION_PHASE': [   {   'bitmask': False,
                                                          'datatype': 'enum',
                                                          'name': 'MissionPhase'}]},
                  'System': {   'CONTROL': [],
                                'FLIGHT': [   {   'bitmask': False,
                                                  'datatype': 'enum',
                                                  'name': 'FlightMode'},
                                              {   'bitmask': False,
                                                  'datatype': 'int',
                                                  'name': 'airspeed'},
                                              {   'bitmask': False,
                                                  'datatype': 'int',
                                                  'name': 'groundspeed'},
                                              {   'bitmask': False,
                                                  'datatype': 'int',
                                                  'name': 'heading'},
                                              {   'bitmask': False,
                                                  'datatype': 'int',
                                                  'name': 'msl_alt'},
                                              {   'bitmask': False,
                                                  'datatype': 'bytes',
                                                  'name': 'packed_mgrs'}],
                                'FUEL': [],
                                'INAV': [   {   'bitmask': False,
                                                'datatype': 'int',
                                                'name': 'inavmodes'},
                                            {   'bitmask': False,
                                                'datatype': 'int',
                                                'name': 'airspeed'},
                                            {   'bitmask': False,
                                                'datatype': 'int',
                                                'name': 'groundspeed'},
                                            {   'bitmask': False,
                                                'datatype': 'int',
                                                'name': 'heading'},
                                            {   'bitmask': False,
                                                'datatype': 'int',
                                                'name': 'msl_alt'},
                                            {   'bitmask': False,
                                                'datatype': 'bytes',
                                                'name': 'packed_mgrs'}],
                                'NAV': [],
                                'NAVIGATION': [],
                                'PAYLOAD': [],
                                'POSITION': [   {   'bitmask': False,
                                                    'datatype': 'bytes',
                                                    'name': 'packed_mgrs'}],
                                'RADIO': [],
                                'SYSTEMS': []}},
    'Testing': {   'System': {   'BINMSG': [   {   'bitmask': False,
                                                   'datatype': 'bytes',
                                                   'name': 'data'}],
                                 'TEXTMSG': [   {   'bitmask': False,
                                                    'datatype': 'bytes',
                                                    'name': 'textdata'}]}}}